on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/3043030d7e29a4f22a72efa77c51e2e6
          gist_title: 20-bluetoothHC05-CCS-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/HC05.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/6b6ce4cbfa0c5c85c2fd55d9f78cec88
          gist_title: 20-BluetoothHC05-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/HC05.c
          file_encoding: WINDOWS-1252